### ISSUE TITLE
This is dumb

### ISSUE THREAD

**Issue by ibrahimk157** [BoxOfDevs/SwitchFromLeet#3]
You guys are legit stupid.

**Comment by HimbeersaftLP** [comment]
And so are you :D

**Comment by hcortezr** [comment]
Dumb af

**Comment by Vaults1** [comment]
Says the guy whose GitHub account has nothing. Stealing people's work is like stealing your money. If you honestly don't care, I'll take £500 and see what you think. (@ibrahimk157)

**Comment by HimbeersaftLP** [comment]
Repo ban percentage for @ibrahimk157 and @eDroiid:
<div style="margin: auto; text-align: center; width: 30%;" title="99%"><div style="text-align: left; margin: 2px auto; font-size: 0px; line-height: 0px; background: #DDDDDD; overflow: hidden; "><div style="font-size: 0px; line-height: 0px; height: 10px; min-width: 0%; max-width: 99%; width: 99%; background: #1D3D8D; "></div></div><div style="font-size: 8pt; font-family: sans-serif; ">99%</div></div>

**Comment by AvgZing** [comment]
Make it 100% org ban

**Comment by lavender-sys** [comment]
@HimbeersaftLP That'll burn. xD

**Comment by AvgZing** [comment]
Done already XD

**Comment by lavender-sys** [comment]
?

**Comment by AvgZing** [comment]
Already Banned, I mean
