### ISSUE TITLE
Why just leet?

### ISSUE THREAD

**Issue by Vaults1** [BoxOfDevs/SwitchFromLeet#4]
Why don't we compare all the server providers?

**Comment by Ad5001** [comment]
Because they're (one of) the worst host for PE "servers" (because you're not even the owner of your server)

**Comment by Vaults1** [comment]
I'm just saying, we should compare all the hosts. But I guess you're right. 😜

**Comment by Ad5001** [comment]
As i said, there are some other hoster like this too. But we don't know them.

**Comment by HimbeersaftLP** [comment]
Leet is the most well-known page. This website will also only be recommending hosts with a good reputation and full control over your server, so that people can enjoy vanilla pmmp/spoon experience
